server:
  port: 9090
  tomcat:
    threads:
      max: 10
      min-spare: 5
    max-connections: 2000
    accept-count: 200
    connection-timeout: 10000
spring:
  datasource:
    username: #YOUR DATABASE LOGIN ACCOUNT
    password: #YOUR DATABASE LOGIN PASSWORD
    url: #YOUR DATABASE LOGIN URL
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: #YOUR DRUID LOGIN ACCOUNT
        login-password: #YOUR DRUID LOGIN PASSWORD
        reset-enable: false
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            delete-allow: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-aliases-package: com.kivy0000.login_web.beans
  mapper-locations: classpath:mapper/*.xml
mailutil:
  default-sender:  #Your sender's email
  default-password: #Your sender's email authorization code